apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: documentId
          matcherRegex: '"documentId":"([^"]+)"'
          url: '/explore?left={"datasource":"loki","queries":[{"expr":"{project=\"planelyx\"} |= \"$${__value.raw}\""}]}'
          datasourceUid: loki
