- targets: ['host.docker.internal:8080']
  labels:
    job: planelyx-api
    project: planelyx
    __metrics_path__: /actuator/prometheus

- targets: ['ocr:8080']
  labels:
    job: planelyx-ocr
    project: planelyx
    __metrics_path__: /metrics
